"use client";

import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { AlertTriangle, CheckCircle } from 'lucide-react';
import { usePrivacyStore } from '@/lib/store';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';

export const DisclaimerModal: React.FC = () => {
  const { hasAcceptedDisclaimer, setHasAcceptedDisclaimer } = usePrivacyStore();

  if (hasAcceptedDisclaimer) return null;

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.9, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.9, y: 20 }}
          className="w-full max-w-lg"
        >
          <Card className="relative overflow-hidden border-yellow-500/50 bg-slate-900 shadow-2xl">
            <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-yellow-500 via-orange-500 to-yellow-500" />
            
            <div className="p-6 md:p-8">
              <div className="flex items-center gap-4 mb-6">
                <div className="p-3 rounded-full bg-yellow-500/10 text-yellow-500">
                  <AlertTriangle size={32} />
                </div>
                <h2 className="text-2xl font-bold text-white">Analysis Disclaimer</h2>
              </div>
              
              <div className="space-y-4 text-slate-300">
                <p>
                  Welcome to <span className="text-indigo-400 font-semibold">ResumeAI</span>. Before you proceed with your resume analysis, please understand the following:
                </p>
                
                <ul className="space-y-3 list-none">
                  {[
                    "AI and algorithmic analyses are not 100% accurate and should be used as a guide only.",
                    "ATS scores are estimates based on common industry patterns and may not match specific company systems.",
                    "Suggested improvements are generated by AI and should be reviewed for factual accuracy before use.",
                    "Final hiring decisions are made by humans; our tool is designed to assist, not replace, professional judgment."
                  ].map((item, i) => (
                    <li key={i} className="flex gap-3">
                      <div className="mt-1.5 shrink-0">
                        <CheckCircle size={16} className="text-indigo-400" />
                      </div>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
                
                <p className="pt-4 text-sm text-slate-400 italic">
                  By clicking "I Understand", you acknowledge these limitations and agree to use the analysis responsibly.
                </p>
              </div>
              
              <div className="mt-8">
                <Button 
                  onClick={() => setHasAcceptedDisclaimer(true)}
                  className="w-full py-6 text-lg font-bold bg-indigo-600 hover:bg-indigo-500 text-white shadow-lg shadow-indigo-600/20"
                >
                  I Understand & Accept
                </Button>
              </div>
            </div>
          </Card>
        </motion.div>
      </div>
    </AnimatePresence>
  );
};
